import Image from 'next/image';
import React from 'react';
import { useShowAnimationContext } from '../../context/ShowAnimationContext';
import { AnimationType, AvailableColors } from '../../enums';
import { Anchor } from '../utils/Anchor';
import { SpanFillAnimated } from '../utils/TextFillAnimation';

interface Props {}

export const About: React.FC<Props> = () => {
  const animationRefImg = useShowAnimationContext<HTMLDivElement>(AnimationType.right);
  const animationRefContent = useShowAnimationContext<HTMLDivElement>(AnimationType.left);

  return (
    <>
      <div className='w-2/3 max-w-sm' ref={animationRefImg}>
        <Image
          width={1080}
          height={441}
          src='/assets/me.jpeg'
          alt='my pic'
          className='rounded-custom w-100'
        />
      </div>
      <div className='text-center text-white desktop:text-left' ref={animationRefContent}>
        <h4 className='my-10 h1 tablet:my-6 desktop:mt-0'>Hey</h4>
        <p className='p-m max-w-[584px] desktop:mr-24'>
          I write code and it&#39;s what I love to do.
          <br />
          Frontend developer based in Italy passionate about cars, Nordic countries and backend
          technologies.
          <br />
          You can contact me or find some free time projects on my&nbsp;
          <Anchor
            label={<SpanFillAnimated label='Github' color={AvailableColors.goodGreen} underline />}
            url='https://github.com/andreachirico11'
          />
          &nbsp;and if you&#39;re interested my resume can be generated by this website.
        </p>
      </div>
    </>
  );
};
